export type PhraseCategory =
  | "quick"
  | "subject"
  | "tense"
  | "be"
  | "helping"
  | "action"
  | "describe"
  | "intensifier"
  | "little"
  | "things"
  | "food"
  | "place"
  | "preposition"
  | "time"
  | "feeling"
  | "connector"
  | "polite";

export type Phrase = {
  id: string;
  label: string;
  category: PhraseCategory;
};

export type PhraseSectionData = {
  id: PhraseCategory;
  title: string;
  eyebrow: string;
  tone: "sky" | "indigo" | "emerald" | "amber" | "rose" | "teal" | "violet" | "slate" | "cyan";
  phrases: Phrase[];
};

const makePhrases = (category: PhraseCategory, labels: string[]): Phrase[] =>
  Array.from(new Set(labels)).map((label) => ({
    id: `${category}-${label.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
    label,
    category,
  }));

export const addressablePeople = ["Mom", "Dad", "Cagatay", "Brother", "Sister"] as const;

export const phraseSections: PhraseSectionData[] = [
  {
    id: "quick",
    title: "Quick Sentences",
    eyebrow: "Ready",
    tone: "rose",
    phrases: makePhrases("quick", [
      "Can I please have the iPad",
      "Can you please help me",
      "I want to play Roblox",
      "I want to watch YouTube",
      "I need a break",
      "I don't want to wait",
      "I don't like that",
      "I changed my mind",
      "I am hungry",
      "I am thirsty",
      "I am tired",
      "I am overwhelmed",
      "It's not working",
      "Why not",
      "But Mom I really don't want to wait",
      "Can you say it again",
      "Thank you",
      "Can I go to the park with Dad",
    ]),
  },
  {
    id: "subject",
    title: "Who / Subject",
    eyebrow: "Who",
    tone: "sky",
    phrases: makePhrases("subject", [
      "I",
      "you",
      "we",
      "Mom",
      "Dad",
      "Cagatay",
      "Brother",
      "Sister",
      "it",
      "this",
      "that",
      "they",
      "he",
      "she",
      "the iPad",
      "the soup",
    ]),
  },
  {
    id: "tense",
    title: "Time Starters",
    eyebrow: "Start",
    tone: "indigo",
    phrases: makePhrases("tense", [
      "I do",
      "I am doing",
      "I did",
      "I was doing",
      "I have done",
      "I have been doing",
      "I had done",
      "I had been doing",
      "I will do",
      "I will be doing",
      "I will have done",
      "I will have been doing",
      "I am",
      "I was",
      "I have",
      "I have been",
      "I had",
      "I had been",
      "I will",
      "I will be",
      "I will have",
      "I will have been",
    ]),
  },
  {
    id: "be",
    title: "Am / Is / Was",
    eyebrow: "Be",
    tone: "violet",
    phrases: makePhrases("be", ["am", "is", "are", "was", "were", "be", "being", "been"]),
  },
  {
    id: "helping",
    title: "Can / Will / Have",
    eyebrow: "Help",
    tone: "violet",
    phrases: makePhrases("helping", [
      "do",
      "does",
      "did",
      "have",
      "has",
      "had",
      "will",
      "would",
      "can",
      "could",
      "should",
      "may",
      "might",
      "must",
      "don't",
      "doesn't",
      "didn't",
      "can't",
      "won't",
    ]),
  },
  {
    id: "action",
    title: "Action Words",
    eyebrow: "Do",
    tone: "cyan",
    phrases: makePhrases("action", [
      "want",
      "need",
      "have",
      "get",
      "make",
      "take",
      "give",
      "put",
      "open",
      "close",
      "eat",
      "drink",
      "play",
      "watch",
      "use",
      "go",
      "help",
      "wait",
      "stop",
      "finish",
      "choose",
      "say",
      "ask",
      "feel",
      "like",
      "look",
      "find",
      "listen",
      "talk",
      "read",
      "write",
      "unlock",
      "want to",
      "need to",
      "have to",
      "like to",
      "eating",
      "drinking",
      "playing",
      "watching",
      "using",
      "going",
      "helping",
      "waiting",
      "working",
      "finished",
      "ate",
      "drank",
      "played",
      "watched",
      "used",
      "went",
      "helped",
      "waited",
      "done",
      "eaten",
      "played",
      "watched",
      "used",
      "gone",
      "helped",
    ]),
  },
  {
    id: "describe",
    title: "Describing Words",
    eyebrow: "What Like",
    tone: "emerald",
    phrases: makePhrases("describe", [
      "big",
      "small",
      "hot",
      "cold",
      "loud",
      "quiet",
      "easy",
      "hard",
      "good",
      "bad",
      "fun",
      "scary",
      "broken",
      "ready",
      "finished",
      "full",
      "empty",
      "hungry",
      "thirsty",
      "tired",
      "working",
      "safe",
      "unsafe",
      "comfortable",
      "uncomfortable",
      "favorite",
      "different",
      "same",
    ]),
  },
  {
    id: "intensifier",
    title: "Intensifiers",
    eyebrow: "How Much",
    tone: "amber",
    phrases: makePhrases("intensifier", ["very", "really", "so", "too", "a little", "more", "less", "almost", "just", "still", "already"]),
  },
  {
    id: "little",
    title: "Little Words",
    eyebrow: "Glue",
    tone: "slate",
    phrases: makePhrases("little", [
      "the",
      "a",
      "an",
      "my",
      "your",
      "his",
      "her",
      "our",
      "some",
      "more",
      "all",
      "this",
      "that",
      "it",
      "me",
      "you",
      "not",
      "to",
      "too",
      "also",
      "only",
      "one",
      "two",
      "first",
      "next",
      "last",
    ]),
  },
  {
    id: "things",
    title: "Things / Devices",
    eyebrow: "Thing",
    tone: "teal",
    phrases: makePhrases("things", [
      "the iPad",
      "the iPhone",
      "the TV",
      "the charger",
      "the remote",
      "my headphones",
      "my blanket",
      "my toy",
      "my book",
      "the door",
      "the light",
      "Roblox",
      "YouTube",
    ]),
  },
  {
    id: "food",
    title: "Foods / Drinks",
    eyebrow: "Eat",
    tone: "emerald",
    phrases: makePhrases("food", [
      "simit",
      "makarna",
      "peynirli poğaça",
      "çikolata",
      "tatlı",
      "cips",
      "börek",
      "gözleme",
      "pancake",
      "sandviç",
      "elma",
      "meyve",
      "sebze",
      "çorba",
      "some dessert",
      "some snacks",
      "water",
      "juice",
      "milk",
      "dinner",
      "breakfast",
      "lunch",
    ]),
  },
  {
    id: "place",
    title: "Places",
    eyebrow: "Where",
    tone: "sky",
    phrases: makePhrases("place", [
      "home",
      "school",
      "outside",
      "the kitchen",
      "the bathroom",
      "the car",
      "the park",
      "the store",
      "grandma's house",
      "my room",
      "upstairs",
      "downstairs",
      "here",
      "there",
    ]),
  },
  {
    id: "preposition",
    title: "Prepositions",
    eyebrow: "Link",
    tone: "amber",
    phrases: makePhrases("preposition", [
      "to",
      "with",
      "for",
      "in",
      "on",
      "at",
      "by",
      "from",
      "under",
      "over",
      "inside",
      "outside",
      "next to",
      "near",
      "around",
      "before",
      "after",
      "until",
      "because of",
    ]),
  },
  {
    id: "time",
    title: "Time Words",
    eyebrow: "When",
    tone: "cyan",
    phrases: makePhrases("time", [
      "now",
      "later",
      "today",
      "tomorrow",
      "yesterday",
      "tonight",
      "after dinner",
      "after school",
      "before bed",
      "in 5 minutes",
      "for 5 minutes",
      "for 10 minutes",
      "when you're done",
      "every day",
      "again",
    ]),
  },
  {
    id: "feeling",
    title: "Feelings / Answers",
    eyebrow: "Say",
    tone: "rose",
    phrases: makePhrases("feeling", [
      "yes",
      "no",
      "okay",
      "not yet",
      "done",
      "all done",
      "happy",
      "sad",
      "mad",
      "upset",
      "tired",
      "hungry",
      "thirsty",
      "overwhelmed",
      "confused",
      "I changed my mind",
      "I don't understand",
      "I need a break",
      "I don't know",
      "I know",
      "I want to try",
      "I don't want to try",
    ]),
  },
  {
    id: "connector",
    title: "Connectors / Longer Sentences",
    eyebrow: "Longer",
    tone: "slate",
    phrases: makePhrases("connector", [
      "and",
      "but",
      "or",
      "because",
      "so",
      "then",
      "if",
      "when",
      "while",
      "before",
      "after",
      "even though",
      "I think",
      "I know",
      "I don't know",
      "I mean",
      "maybe",
      "actually",
      "instead",
    ]),
  },
  {
    id: "polite",
    title: "Polite Endings",
    eyebrow: "Kind",
    tone: "amber",
    phrases: makePhrases("polite", [
      "please",
      "thank you",
      "no thank you",
      "excuse me",
      "I'm sorry",
      "can you please",
      "may I please",
      "I don't understand",
      "can you say it again",
    ]),
  },
];

export const people = new Set<string>(addressablePeople);

export type FavoritePhrase = {
  id: string;
  label: string;
  words: string[];
};

export const favoritePhrases: FavoritePhrase[] = [
  {
    id: "ipad-please",
    label: "Can I please have the iPad?",
    words: ["Can", "I", "please", "have", "the", "iPad"],
  },
  {
    id: "help-me",
    label: "Can you please help me?",
    words: ["Can", "you", "please", "help", "me"],
  },
  {
    id: "youtube",
    label: "I want to watch YouTube.",
    words: ["I", "want", "to", "watch", "YouTube"],
  },
  {
    id: "thank-you",
    label: "Thank you.",
    words: ["Thank", "you"],
  },
];
